# Generated by Django 3.0.11 on 2021-02-20 21:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210218_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='referencia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='codigo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
